# Uncomment this line if you're using Swift
use_frameworks!


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
            config.build_settings['SWIFT_VERSION'] = '3.0'
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end


target 'HFCardCollectionViewLayoutExample' do
    platform :ios, '10.0'
    pod 'HFCardCollectionViewLayout', :path => '../'
end
